sudo: required
services:
  - docker

before_install:
  - docker build -t lcs-grtsch/dep_test -f Dockerfile.dev .

script:
  - docker run lcs-grtsch/dep_test

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
